"use client";

import { Provider } from "react-redux";
import "./globals.css";
import { Inter } from "next/font/google";
import appStore from "@/utils/appStore";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Provider store={appStore}>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </Provider>
  );
}
